msg="Python Kursuna Hoşgeldiniz. Ben Furkan Özkan"
result=msg.upper()
print(result)
result=msg.lower()
print(result)
result=msg.title()
print(result)
result=msg.capitalize()
print(result)
result=msg.islower()
print(result)
result=msg.isupper()
print(result)
result=" aaa   ".strip()
print(result)
result=msg.split()
print(result)
print(result[0])
print(result[-1])
result=msg.split(".")
print(result)
result=".".join(result)
print(result)
result=msg.index("Furkan")
print(result)
result=msg.startswith("Pyt")
print(result)